const display=document.getElementById("display");
const errorBox=document.getElementById("error");
const keys=document.querySelector(".keys");
function setError(t){errorBox.textContent=t||""}
function insert(v){const s=display.selectionStart,e=display.selectionEnd;const t=display.value;display.value=t.slice(0,s)+v+t.slice(e);const n=s+v.length;display.setSelectionRange(n,n);setError("")}
function backspace(){const s=display.selectionStart,e=display.selectionEnd;const t=display.value;if(s!==e){display.value=t.slice(0,s)+t.slice(e);display.setSelectionRange(s,s)}else if(s>0){display.value=t.slice(0,s-1)+t.slice(s);display.setSelectionRange(s-1,s-1)}setError("")}
function clearAll(){display.value="";setError("")}
function tokenize(s){const tokens=[];let i=0;while(i<s.length){const c=s[i];if(/\s/.test(c)){i++;continue}if(/[0-9.]/.test(c)){let num=c;i++;while(i<s.length&&/[0-9.]/.test(s[i])){num+=s[i];i++}if((num.match(/\./g)||[]).length>1)return{error:"Invalid number"};tokens.push({type:"num",value:Number(num)});continue}if(/[+\-*/%^()]/.test(c)){tokens.push({type:"op",value:c});i++;continue}if(/[a-zA-Z]/.test(c)){let name=c;i++;while(i<s.length&&/[a-zA-Z]/.test(s[i])){name+=s[i];i++}tokens.push({type:"func",value:name});continue}return{error:"Invalid character"}}return{tokens}}
function toRPN(tokens){const out=[],op=[];const prec={"^":4,"*":3,"/":3,"%":3,"+":2,"-":2};const rightAssoc={"^":true};for(let i=0;i<tokens.length;i++){const t=tokens[i];if(t.type==="num")out.push(t);else if(t.type==="func")op.push(t);else if(t.type==="op"){const v=t.value;if(v==="(")op.push(t);else if(v===")"){while(op.length&&op[op.length-1].value!=="(")out.push(op.pop());if(!op.length)return{error:"Mismatched parentheses"};op.pop();if(op.length&&op[op.length-1].type==="func")out.push(op.pop())}else{while(op.length){const top=op[op.length-1];if(top.type==="func")break;if(top.type==="op"){const pTop=prec[top.value]||0,pCur=prec[v]||0;if((rightAssoc[v]&&pCur<pTop)||(!rightAssoc[v]&&pCur<=pTop))out.push(op.pop());else break}else break}op.push(t)}}}
while(op.length){const t=op.pop();if(t.value==="("||t.value===")")return{error:"Mismatched parentheses"};out.push(t)}return{out}}
function evalRPN(rpn){const st=[];for(const t of rpn){if(t.type==="num")st.push(t.value);else if(t.type==="func"){const a=st.pop();if(a===undefined)return{error:"Invalid expression"};if(t.value.toLowerCase()==="sqrt"){if(a<0)return{error:"Square root of negative"};st.push(Math.sqrt(a))}else return{error:"Unknown function"}}else{const b=st.pop(),a=st.pop();if(a===undefined||b===undefined)return{error:"Invalid expression"};switch(t.value){case "+":st.push(a+b);break;case "-":st.push(a-b);break;case "*":st.push(a*b);break;case "/":if(b===0)return{error:"Division by zero"};st.push(a/b);break;case "%":st.push(a%b);break;case "^":st.push(a**b);break;default:return{error:"Unknown operator"}}}}
if(st.length!==1)return{error:"Invalid expression"};return{value:st[0]}}
function calculate(){const s=display.value.trim();if(!s){setError("");return}const tk=tokenize(s);if(tk.error){setError(tk.error);return}const r=toRPN(tk.tokens);if(r.error){setError(r.error);return}const v=evalRPN(r.out);if(v.error){setError(v.error);return}display.value=String(v.value);display.setSelectionRange(display.value.length,display.value.length);setError("")}
keys.addEventListener("click",e=>{const b=e.target;if(!(b instanceof HTMLButtonElement))return;const act=b.dataset.action;const val=b.dataset.value;const f=b.dataset.func;if(act==="clear"){clearAll();return}if(act==="back"){backspace();return}if(act==="equals"){calculate();return}if(act==="func"&&f){insert(f+"(");return}if(val)insert(val)});
display.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();calculate()}else if(e.key==="Escape"){e.preventDefault();clearAll()}else if(e.key==="Backspace"){setError("")}});
window.addEventListener("load",()=>display.focus());